### ISSUE TITLE
Can you add func Reduce(Contract) Selection  -1 line

### ISSUE THREAD

**Issue by 9840380** [aafulei/sublime-expand-selection-to-line-upwards#1]
First of all thanks for that plugins its excellent!!

Can you please add to plugin:

1. **ReduceSelectionFromLineUpwards**

- minus 1 line from Begin

2. **ReduceSelectionFromLineDownwards**

-  minus 1 Line from End

Thanks

**Comment by aafulei** [comment]
Thanks for the suggestion! Sure, I will see if I can do it. Please allow for some time as I am very busy at this moment.

**Comment by aafulei** [comment]
Hi @9840380 sorry for the wait and now the good news - 53b700679adfbfa94028c05ba478007ef051d7f2 (which I call version 4.0.0) delivers this feature 🎉.

I expect PackageControl to pick up this update in 24 hours, and plugin update should be automatic on the user side.

Check the PackageControl [page](https://packagecontrol.io/packages/Expand%20Selection%20to%20Line%20Upwards) to see if it has been picked up.
